version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    assignees:
      - "fwilhe2"
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'gradle'
    directory: '/'
    assignees:
      - "fwilhe2"
    schedule:
      interval: 'weekly'
