name: Perform Release
on:
  workflow_dispatch:
  repository_dispatch:
    types: perform_release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up JDK 17
        uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5.7.0
        with:
          java-version: '17'
          distribution: temurin
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Get Version Number
        id: next_version
        run: |
          echo "version_number=$(npx semver --increment patch $(curl --silent "https://api.github.com/repos/$GITHUB_REPOSITORY/releases/latest" | jq -r .tag_name))" >> "$GITHUB_OUTPUT"
      - run: echo ${{ steps.next_version.outputs.version_number }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@0cb9c9b65d5d1901c1f53e5e66eaf4afd303e70e # v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.next_version.outputs.version_number }}

      - name: Publish to GitHub Packages
        run: ./gradlew publishAllPublicationsToGitHubPackagesRepository
        env:
          USERNAME: fwilhe2
          TOKEN: ${{ secrets.GPR_AUTH_TOKEN }}
          VERSION: ${{ steps.next_version.outputs.version_number }}